name: Check build

on:
  # Событие "push" для веток "main" и "develop"
  push:
    branches: [ main, develop ]

  # Событие "pull_request" для веток "main" и "develop"
  pull_request:
    branches: [ main, develop ]

  # Ручной запуск workflow
  workflow_dispatch:

jobs:
  check_pull_request:
    runs-on: ubuntu-latest

    steps:
      # Шаг для клонирования репозитория
      - uses: actions/checkout@v3
      
      # Шаг для настройки окружения Java с версией 1.17
      - uses: actions/setup-java@v1
        with: { java-version: 1.17 }

      - name: Run detekt on app module
        run: ./gradlew :app:detektCheck

          # Шаг для запуска detekt на модуле 'uikit'
      - name: Run detekt on uikit module
        run: ./gradlew :uikit:detektCheck

          # Шаг для запуска detekt на модуле 'ukitsample'
      - name: Run detekt on ukitsample module
        run: ./gradlew :ukitsample:detektCheck
      
      # Шаг для запуска скрипта сборки проекта
      - name: Run check out script
        run: ./gradlew :app:build

      # Шаг для проверки статуса сборки
      - name: Check status
        run: echo "Check build status"

      # Шаг для установки статуса "failed" в случае ошибки сборки
      - name: Set failed if build failed
        if: failure()
        run: echo "::error::Build failed" 
